# Generated by Django 4.1.9 on 2023-09-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0020_education_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='my_cv/static/my_cv/img/portfolio')),
                ('portfolioskill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_cv.portfolioskills')),
            ],
        ),
    ]
