# Generated by Django 4.1.9 on 2023-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_cv', '0021_portfolioskills_portfolioimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimg',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
